source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# triptri specifics
gem 'rmagick'
gem 'devise'
gem 'carrierwave'
gem 'activeadmin', github: 'activeadmin'
gem 'activeadmin-dragonfly', github: 'stefanoverna/activeadmin-dragonfly'
gem 'activeadmin-wysihtml5', github: 'stefanoverna/activeadmin-wysihtml5'
gem 'brcpfcnpj'
gem 'axlsx_rails'
gem 'stringex'
gem 'redcarpet'
gem 'cocoon'
gem 'pagseguro-oficial', '~> 2.5.0'
gem 'sidekiq'
gem 'cancan'
gem 'mailchimp-api'
gem 'instagram'

# activeadmin
gem 'rails-jquery-autocomplete'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'guard-livereload', '~> 2.4', require: false
  gem 'rack-livereload'
  gem 'rb-fsevent'
end